# Generated by Django 5.0 on 2023-12-29 23:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exassemble', '0004_exsheet_exercises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExSheet',
            new_name='ExerciseSheet',
        ),
    ]
